export * from './Header'
export * from './Body'
export * from './Header'
export * from './Header2'
export * from './Footer'
export * from './MoviePageDashBoard'
export * from './SinglePage'
export * from './GenrePageDashBoard'
